export const LOADING = 'LOADING';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const RESET = 'RESET';

export const MESSAGE_ERROR = 'MESSAGE_ERROR';
export const MESSAGE_SUCCESS = 'MESSAGE_SUCCESS';
export const MESSAGE_INFO = 'MESSAGE_INFO';

export const REGISTRATION_REQUEST = 'REGISTRATION_REQUEST';
export const REGISTRATION_ERROR = 'REGISTRATION_ERROR';
export const VERIFY_PHONE_REQUEST = 'VERIFY_PHONE_REQUEST';
export const VERIFY_PHONE_SUCCESS = 'VERIFY_PHONE_SUCCESS';
export const SIGNIN_REQUEST = 'SIGNIN_REQUEST';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';

export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const VERIFY_RESET_CODE_REQUEST = 'VERIFY_RESET_CODE_REQUEST';
export const VERIFY_RESET_CODE_SUCCESS = 'VERIFY_RESET_CODE_SUCCESS';
export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';

export const USER_INFO_REQUEST = 'USER_INFO_REQUEST';
export const USER_INFO_SUCCESS = 'USER_INFO_SUCCESS';

export const UPDATE_USER_INFO_REQUEST = 'UPDATE_USER_INFO_REQUEST';
export const UPDATE_USER_INFO_SUCCESS = 'UPDATE_USER_INFO_SUCCESS';

export const OVERVIEW_DATA_REQUEST = 'OVERVIEW_DATA_REQUEST';
export const OVERVIEW_DATA_SUCCESS = 'OVERVIEW_DATA_SUCCESS';

export const PAYMENTS_DATA_REQUEST = 'PAYMENTS_DATA_REQUEST';
export const PAYMENTS_DATA_SUCCESS = 'PAYMENTS_DATA_SUCCESS';

export const TRANSACTIONS_DATA_REQUEST = 'TRANSACTIONS_DATA_REQUEST';
export const TRANSACTIONS_DATA_SUCCESS = 'TRANSACTIONS_DATA_SUCCESS';

export const SUBSCRIPTIONS_DATA_REQUEST = 'SUBSCRIPTIONS_DATA_REQUEST';
export const SUBSCRIPTIONS_DATA_SUCCESS = 'SUBSCRIPTIONS_DATA_SUCCESS';

export const NOTIFICATIONS_DATA_REQUEST = 'NOTIFICATIONS_DATA_REQUEST';
export const NOTIFICATIONS_DATA_SUCCESS = 'NOTIFICATIONS_DATA_SUCCESS';
export const NOTIFICATIONS_CLEAR_REQUEST = 'NOTIFICATIONS_CLEAR_REQUEST';
export const NOTIFICATIONS_CLEAR_SUCCESS = 'NOTIFICATIONS_CLEAR_SUCCESS';

export const ACCOUNTS_DATA_REQUEST = 'ACCOUNTS_DATA_REQUEST';
export const ACCOUNTS_DATA_SUCCESS = 'ACCOUNTS_DATA_SUCCESS';

export const SEND_LOG_REQUEST = 'SEND_LOG_REQUEST';

export const TOGGLE_ADD_ACCOUNT = 'TOGGLE_ADD_ACCOUNT';

export const ADD_WALKTHROUGHT_ITEM = 'ADD_WALKTHROUGHT_ITEM';

export const SEND_2FA_REQUEST = 'SEND_2FA_REQUEST';
export const TOGGLE_2FA_REQUEST = 'TOGGLE_2FA_REQUEST';
export const SHOW_2FA = 'SHOW_2FA';

export const WRONG_IMAGE_REQUEST = 'WRONG_IMAGE_REQUEST';
export const WRONG_IMAGE_SUCCESS = 'WRONG_IMAGE_SUCCESS';

export const ADD_EMPATHIZE_SUBSCRIPTION_REQUEST =
  'ADD_EMPATHIZE_SUBSCRIPTION_REQUEST';
export const ADD_EMPATHIZE_SUBSCRIPTION_SUCCESS =
  'ADD_EMPATHIZE_SUBSCRIPTION_SUCCESS';
export const CANCEL_EMPATHIZE_SUBSCRIPTION_REQUEST =
  'CANCEL_EMPATHIZE_SUBSCRIPTION_REQUEST';
export const CANCEL_EMPATHIZE_SUBSCRIPTION_SUCCESS =
  'CANCEL_EMPATHIZE_SUBSCRIPTION_SUCCESS';
export const RESET_EMPATHIZE_SUBSCRIPTION_REQUEST =
  'RESET_EMPATHIZE_SUBSCRIPTION_REQUEST';
export const RESET_EMPATHIZE_SUBSCRIPTION_SUCCESS =
  'RESET_EMPATHIZE_SUBSCRIPTION_SUCCESS';

export const BILLING_DATE_REQUEST = 'BILLING_DATE_REQUEST';
export const BILLING_DATE_SUCCESS = 'BILLING_DATE_SUCCESS';
